### ISSUE TITLE
It not possible to install pylops!

### ISSUE THREAD

**Issue by RezaMohammadi2023** [PyLops/pylops#510]
Dear All 
the following errors occur when I try to install pylops using pip or conda. Please let me know what to do.

using pip
Collecting pylops
  Using cached pylops-2.1.0-py3-none-any.whl (275 kB)
Requirement already satisfied: scipy>=1.4.0 in c:\users\mohamadi\anaconda3\lib\site-packages (from pylops) (1.6.2)
Collecting numpy>=1.21.0
  Downloading numpy-1.24.3-cp38-cp38-win_amd64.whl (14.9 MB)
Note: you may need to restart the kernel to use updated packages.
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/1a/62/af7e78a12207608b23e3b2e248fc823fbef75f17d5defc8a127c5661daca/numpy-1.24.3-cp38-cp38-win_amd64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\mohamadi\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mohamadi\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\mohamadi\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\mohamadi\anaconda3\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\mohamadi\anaconda3\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Users\mohamadi\anaconda3\lib\http\client.py", line 502, in readinto
.
...

usnig conda:

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... failed

Note: you may need to restart the kernel to use updated packages.

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//conda.anaconda.org/conda-forge/win-64'

**Comment by mrava87** [comment]
Hello, it seems like you are having internet issues, your installation fails as you are not able to retrieve some packages.

Please try again with a stable internet connection. I am not sure what you mean double-clicking the setup.py file, this won’t work. If you want to install from source follow our guidelines for developers in the README file :)

**Comment by mrava87** [comment]
@RezaMohammadi2023 I assume you managed given that you didn't send any further message?
